# Generated by Django 4.1.2 on 2022-10-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0009_post_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippets',
            field=models.CharField(max_length=200),
        ),
    ]
