# Generated by Django 4.1.2 on 2022-10-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0021_alter_post_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_snippets',
            field=models.CharField(default='coding', max_length=20),
        ),
    ]
