# Generated by Django 4.1.2 on 2022-10-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0022_post_title_snippets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_snippets',
            field=models.CharField(default='Read This Article', max_length=20),
        ),
    ]
