# Generated by Django 4.1.2 on 2022-10-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0023_alter_post_title_snippets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_snippets',
        ),
    ]
