# Generated by Django 4.1.2 on 2022-10-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0024_remove_post_title_snippets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
