# Generated by Django 4.1.2 on 2022-10-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0025_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
    ]
