# Generated by Django 4.1.2 on 2022-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0029_category_catg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catg_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
