# Generated by Django 4.1.2 on 2022-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0031_remove_category_catg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippets',
            field=models.CharField(max_length=200),
        ),
    ]
